# Settings for block break.
BlockBreak:
  Handle-XP: true
  Whitelist: false # if True, use a whitelist, otherwise use a blacklist for the items specified below.
  Items: []

# Settings for killing.
Kill:
  Handle-XP: true
  Whitelist: false
  Items: []