name: AutoRelease

on:
  push:
    tags:
      - '*.*-V*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew
      
      - name: Build with Gradle
        run: ./gradlew assemble

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'dev') }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: 53bLuKoa
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          version-type: ${{ contains(github.ref, 'dev') && 'beta' || 'release' }}
          files: "build/libs/*.jar"
          changelog: ${{ github.event.head_commit.message }}
          version-name: "Reduced Drops - ${{ github.ref }}"
          version-number: "${{ github.ref }}"
          featured: true
          loaders: |
            spigot
            paper
            purpur
            folia
          game-versions: |
            >=1.20
